### ISSUE TITLE
Composition of  Composite Variants seems to be unavailable through API

### ISSUE THREAD

**Issue by RevMen** [tradegecko/smaug#10]
I need to be able to know the Variants and their quantities that make up a Composite Variant. As far as I can tell, the API only has the ability to tell me that the Variant associated with a Order Line Item is a composite through the `composite` flag, but it tells me nothing about the variants that make up that composite. Is there a way to determine the composition of a Composite Variant that I'm just not seeing the documentation?

**Comment by lcpriest** [comment]
It's currently undocumented, but I believe the end point is something like '/variants/:id/composition'.
  
  

  
  
>

**Comment by RevMen** [comment]
`/variants/:id/composition` works! Thank you

**Comment by AgilityCC** [comment]
This seems like a break from the APIs current approach.  Is the long range plan to implement this like variant_prices, locations, prices, and other arrays on the Variant object itself?

Also, it has been over a year as being undocumented.  Maybe it is time to fully implement and document?
