### ISSUE TITLE
Question: File import not found or unreadable: @tradegecko/styles/scss/settings/base-colours

### ISSUE THREAD

**Issue by pedr0-fr** [tradegecko/smaug#100]
Operating system:Ubuntu 18.04
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): 17b259a40da6ef3e0561db76371754b6620e1e43
Browser version(s): latest chrome version 83.0.4103.106
Ruby version (run `ruby -v`): 2.6.5

Came here from [slate](https://github.com/slatedocs/slate/wiki/Custom-Slate-Themes#other-peoples-slate-theming) but not sure whether someone from outside of Tradegecko is supposed to run this?

Not sure what I am supposed to fill in ".env file":
OAUTH_SECRET=xxx
OAUTH_ID=xxx
OAUTH_TOKEN=xxx

npm install fails on this dependency: https://github.com/tradegecko/tradegecko-assets.git
This repository seems private, think I just wasted my time trying to run something I wasn't supposed to...

**Comment by ryancyq** [comment]
Hi @pedr0-fr you can take a look at our developer site https://developer.tradegecko.com/ which was built with customised slate theming.
