### ISSUE TITLE
Question: Get archived/voided orders

### ISSUE THREAD

**Issue by unclethehornet** [tradegecko/smaug#111]
Hi TG team,

Is it possible to get a list of recently voided sales orders?

I've tried the following query, but no results are returned (and there are voided orders - although they disappear from the UI as well).

https://api.tradegecko.com/orders?status=archived&page=1&limit=250&updated_at_min=2020-07-10T20:37:20

Regards,

David.

**Comment by ryancyq** [comment]
Hi @unclethehornet 

For deleted orders in `draft` status , please filter it by `deleted`
For deleted orders after active status, please filter it by `void`


For your case, the following query will be able to retrieve recently voided sales orders

https://api.tradegecko.com/orders?status=void&page=1&limit=25&updated_at_min=2020-07-10T20:37:20

**Comment by unclethehornet** [comment]
This worked.  Great.  Thanks.  

Possibly, the API docs could be updated to reflect this:

https://developer.tradegecko.com/docs.html#order

< status | Possible options are draft, active, finalized
> status | Possible options are draft, active, finalized, deleted, void
