### ISSUE TITLE
Not able to fetch order id from order line items api

### ISSUE THREAD

**Issue by parthshah27** [tradegecko/smaug#122]
Hello,
I want to fetch order_id from order line item api call is there any way to fetch order id from order line item api ?
I was firing below url but that's not working
https://api.tradegecko.com/order_line_items?order_id=103473108

**Comment by pmdeazeta** [comment]
You can use side loading
https://api.tradegecko.com/orders/103473108?include=order_line_items

**Comment by ryancyq** [comment]
@parthshah27 `order_id` is a supported filtering attribute on `order_line_items` endpoint. 

Could you share more details on I was firing below url but that's not working
https://api.tradegecko.com/order_line_items?order_id=103473108

**Comment by parthshah27** [comment]
> You can use side loading
> https://api.tradegecko.com/orders/103473108?include=order_line_items

Thanks this worked for me
