### ISSUE TITLE
Getting Available stock on variant

### ISSUE THREAD

**Issue by soberanes** [tradegecko/smaug#13]
Hi.

I'm trying to get the the stock available in variant object. It only retrieve the stock_on_hands in locations array. How can I get this? I don't know if this is possible.

Ref: https://api.tradegecko.com/variants/ID

**Comment by gherry** [comment]
Hi @soberanes,

Stock Available that is shown in our app is a derivation from `stock_on_hand` and `committed_stock`. 
So, `available_stock = stock_on_hand - committed_stock`

**Comment by soberanes** [comment]
Thanks @gherry I didn't understand the Tradegecko terms about stocks.
