### ISSUE TITLE
Contacts without a company

### ISSUE THREAD

**Issue by ethancalvo** [tradegecko/smaug#14]
The method for creating a contact requires a company_id. What is the preferred method for creating customers that are not associated with a company? 

Do you just create a company called "Consumer?"

**Comment by gherry** [comment]
Hi @ethancalvo,

Yes, `company_type: consumer` is created for this purpose. Retail or e-commerce customer is the generally created as company with type `consumer`

**Comment by ethancalvo** [comment]
It might be cool to allow custom company_types.  For instance, we sell to schools, non-profits, and individual consumers. Is that what you guys are using tags for? If so, have you published the api for attaching tags to items?

**Comment by bradleypriest** [comment]
We have custom company_types down as a feature request, no timeline or confirmation on that just yet though.
Just updated the docs to make sure tags are on the company as well, cheers!
