### ISSUE TITLE
New application authorization issue:

### ISSUE THREAD

**Issue by bhargavjainog** [tradegecko/smaug#17]
I have an issue while authorizing my application, specifically with redirect_URL.

I am getting "The redirect uri included is not valid." error while hitting at **"auth/tradegecko"** endpoint from local.

Callback_URLs in application information is **http://localhost:3000/auth/** 

When I click on **Authorize** button manually on tradegecko portal it gets redirected to page http://localhost:3000/auth/?code=sampletoken and works fine But when my application hit to  **"auth/tradegecko"** end point , It gets redirected to:
 **https://go.tradegecko.com/oauth/authorize?client_id=sampleId&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Ftradegecko%2Fcallback&response_type=code&state=ebae3954f0d0a9e301c8a002b82cbc7540b9249470539f08** and states error:

The redirect uri included is not valid.

My Application name is : Commissions

Please help me with the solution.

**Comment by bradleypriest** [comment]
Hi @bhargavjainog your callback URLs have to exactly match, it looks like you're passing in `localhost:3000/auth/tradegecko/callback` as your callback URL during the handshake rather than `localhost:3000/auth/` which is set in the app.
I'd suggest updating the callback URL to the full value

**Comment by bhargavjainog** [comment]
Hello ,

Thanks for your reply.

How does we pass URL while hamdshake.

I thought only way to mention callback URL is in application fields on
tradegecko portal which I have done as localhost:3000/auth/ and I am
expexting my application to point there.

I have no idea where else I have mentioned callback url as
localhost:3000/auth/tradegecko/callback
.

Please help me with this.

Regards,
Bhargav

**Comment by bradleypriest** [comment]
Hi bhargavjainog, are you using a library to make the OAuth handshake? If so which one

**Comment by bhargavjainog** [comment]
I am using tradegecko omniauth only.

**Comment by bradleypriest** [comment]
Ahh, in that case, that is the callback URL hardcoded into the omniauth library (not the TG specific one, the core omniauth library).
Easiest way forward is to probably just update your app to support /auth/tradegecko/callback.

If not, then take a look at the omniauth docs here https://github.com/intridea/omniauth

**Comment by bhargavjainog** [comment]
Hello,

Thank you so much for your knowledge and help.
Can you please help me with full URL i should update in application call
back url field on TG portal?

It will help me.

Regards,
Bhargav

**Comment by bradleypriest** [comment]
It's http://localhost:3000/auth/tradegecko/callback

**Comment by bhargavjainog** [comment]
It was this error after matching the URL as suggested.

Regards,
Bhargav

**Comment by bhargavjainog** [comment]
Sorry the latest error was as below.

Regards,
Bhargav

**Comment by bhargavjainog** [comment]
I will be glad if you could specify the best library for handshake if this
oauth2 is not much popular.

Regards,
Bhargav

**Comment by bradleypriest** [comment]
`omniauth-tradegecko` is the best option, we use it for many internal applications.
You just need to set up your auth URLs correctly in your TradeGecko OAuth application section and it'll work perfectly.

**Comment by bhargavjainog** [comment]
Hello ,

Can you please give me the latest omniauth-tradegecko gem version and if
possible the github link of any example available.

I have already spent much time and need to proceed quickly.

Regards,
Bhargav

**Comment by bradleypriest** [comment]
Hi @bhargavjainog the latest version is on Rubygems and is 0.1.2, but almost any version will work.
There is an example Rails app at https://github.com/tradegecko/tradegecko-example-app
If you can let me know your account name, I'm happy to double check the callback URL from our side for you

**Comment by bhargavjainog** [comment]
Company name : Jasz Couture
Application name : commisions

**Comment by bradleypriest** [comment]
Other than switching from 127.0.0.1 to localhost, the redirect URI looks fine.
What is the issue you're running into now?

**Comment by bhargavjainog** [comment]
I changed Application Callback url to
http://localhost:3000/auth/tradegecko/callback.

Currently after hitting at auth endpoint og TG, application is redirected
to
http://localhost:3000/auth/tradegecko/callback?code=5ba67408192944b46ef7144c2abd0149152e93f48f7024e1aadcdf7642f45ca2&state=213791ba44c28482f96aafb2f18c73bae1f13d19195442d2
.

But page says error,

**Comment by bhargavjainog** [comment]
I changed Application Callback url to
http://localhost:3000/auth/tradegecko/callback.

Currently after hitting at auth endpoint og TG, application is redirected
to
http://localhost:3000/auth/tradegecko/callback?code=5ba67408192944b46ef7144c2abd0149152e93f48f7024e1aadcdf7642f45ca2&state=213791ba44c28482f96aafb2f18c73bae1f13d19195442d2
.

But page says error,
OAuth2::Error invalid_redirect_uri: The redirect uri included is not valid.
{"error":"invalid_redirect_uri","error_description":"The redirect uri
included is not valid."}

I have provided the snapshot.

**Comment by bhargavjainog** [comment]
Hello,

Can someone please guide me through this?

It seems that I have changed my callback URL as per TG Omniauth requirement
and my page is redirected correctly but Oauth didn't like that as I have
mentioned in previous screen shot.

Regards,
Bhargav

**Comment by bhargavjainog** [comment]
There were conflicting entries in gemfile , cleaning gemfile and reinstalling everything worked.
Thank you so much.
