### ISSUE TITLE
Question: Can a custom date be used for Order Flow actions?

### ISSUE THREAD

**Issue by ethancalvo** [tradegecko/smaug#19]
There are currently 4 actions you can do on an invoice that all require a post
1 . Invoice the order POST /orders/[:order_id]/actions/invoice
2 . Pay the order POST /orders/[:order_id]/actions/pay
3 . Create a Package for Shipping POST /orders/[:order_id]/actions/pack
4 . Ship the package POST /orders/[:order_id]/actions/fulfil

Pack and fulfill seem to use the issued_at date, but invoice and pay use the date/time of the Post.
Is it possible to include a date for when these should have happened?
I would like to be able to set a property like "date" in a post body for these items.

**Comment by bradleypriest** [comment]
Hi Ethan, right now the action endpoints don't take any parameters at all, they just the same defaults as just hitting the buttons in app. 

If you want to customize some of the fields, you can have full control over the objects by creating a fulfillment via the fulfillments endpoint. 

Cheers,
Brad
