### ISSUE TITLE
Question: Can I set a purchase order to "Received" using TradeGecko API?

### ISSUE THREAD

**Issue by kevagc** [tradegecko/smaug#20]
I am having some issues with purchase_order.

I created a purchase_order using the API and save the status as "Received". However, when I go into the TradeGecko.com, the status is "Received" but Tradegecko doesn't recognize the purchase order as being received. 

Can you help me out here? What must I do in the API to set a purchase order to "Received"?

**Comment by bradleypriest** [comment]
Hi @kevagc, the status field is readonly based on the lifecycle of the PO.
To move a Purchase Order to received, you must receive all the goods inside that Purchase Order, by creating the relevant procurement objects.

However that hasn't been documented yet as it's still subject to change. (See https://github.com/tradegecko/smaug/issues/5)

If you'd like to use it anyway, under the caveat that they may still change, I suggest taking a look at the API calls the web app currently makes and copy those as it uses the same API actions.

**Comment by kevagc** [comment]
Hi @bradleypriest , thanks for your speedy comments!

I tried doing a PUT https://api.tradegecko.com/procurements/ but it returned the markup for your 404 page. Couldn't get any clues from the Tradegecko UI too. Could you let us know what are the calls we need to make to create the procurements?

**Comment by bradleypriest** [comment]
Hi Kevin,
Do you mean POST? PUT is for updates to existing objects. 

I don't have any data on hand, but if you just open up the chrome inspector when you hit receive on a Purchase Order, you can inspect the Ajax request for structure.
