### ISSUE TITLE
Cannot refresh access_token

### ISSUE THREAD

**Issue by ungureanuliviu** [tradegecko/smaug#25]
Hi,

Somehow I can't get the refresh_token request to work: the response is always an error like

>  [message:protected] => Client error: `POST https://api.tradegecko.com/oauth/token` resulted in a `401 Unauthorized` response:
> {"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported par (truncated...)

My request:
```
$opts = [
            'json'    => [
                "client_id"      => $tg[ 'api_client_id' ],
                "client_secret"  => $tg[ 'api_secret' ],
                "redirect_uri"   => WEBSITE_URL.'/auth/vendors/connect/trade-gecko',
                "grant_type"     => "refresh_token",
                'refresh_token ' => $this->refreshAccessToken,
            ],
            'headers' => [
                'Content-type' => 'application/json',
            ],
        ];

        $res = $this->client->post('/oauth/token', $opts);
        $tradeGeckoResponse = json_decode($res->getBody()->getContents(), true);
```
If I try to authorize my app again it will work another 2h.
The interesting thing is if I try to refresh the token just after I receive it.. the same error appears.

I'm missing something here? I tried to send the Authorization header as well but without any success.

Thank you

**Comment by bradleypriest** [comment]
Hi @ungureanuliviu, sadly we don't really have any PHP devs in-house.

This is the standard OAuth 2 refresh flow, may I suggest either using an OAuth library to handle it for you or ask for some help on StackOverflow.

Cheers,
Brad
