### ISSUE TITLE
Question: Tradegecko webhooks

### ISSUE THREAD

**Issue by ungureanuliviu** [tradegecko/smaug#26]
Hi,

Does Tradegecko provide any webhooks for getting notified when order status changed?

Thanks.

**Comment by lcpriest** [comment]
Currently there are no order status webhooks, but you can hook into fulfillment.create, 'invoice.create' and 'payment.create' webhooks.

**Comment by futtersack** [comment]
Hello @lcpriest,
I find no documentation on how to use Tradegecko hooks. I don't create a new issue as the title of the question could be related to mine and as other people could be interested.
Thanks!

**Comment by futtersack** [comment]
@bradleypriest, any ideas?

**Comment by futtersack** [comment]
Hello again,
@lcpriest you said it is possible to use invoice creation webhook and others, is there any for products operations? Where can we configure the callback url? @bradleypriest any ideas??

**Comment by bradleypriest** [comment]
Hi @futtersack sorry about the delay.
The webhook documentation and functionality is still under development.
I can share with you, what's available right now, although we reserve the right to adjust up until we publish 1.0.
That being said there is unlikely to be any changes to webhooks and if there are, we'll make sure to notify API users beforehand.

```
### Create webhook
### Available Events
  # EVENTS = %w[
  #   account.update
  #   address.create
  #   address.update
  #   company.create
  #   company.update
  #   contact.create
  #   contact.update
  #   fulfillment.create
  #   fulfillment_return.create
  #   invoice.create
  #   location.create
  #   location.update
  #   order.create
  #   payment.create
  #   product.create
  #   procurement.create
  #   purchase_order.create
  #   stock_adjustment.create
  #   stock_transfer.create
  #   variant.create
  #   variant_image.create
  # ]
curl -X POST -H "Content-type: application/json" -H "Authorization: Bearer 7f2ba72ae693b57e18" https://api.tradegecko.com/webhooks -d '{"webhook":{"address":"http://localhost:3000/webhooks": ,"event":"product.create"}}'

### Update Webhook

curl -X POST -H "Content-type: application/json" -H "Authorization: Bearer 7f2ba72ae693b57e18" https://api.tradegecko.com/webhooks/1 -d '{"webhook":{"address":"http://localhost:3000/webhooks": ,"event":"product.create"}}'

### Delete webhook

curl -X DELETE -H "Content-type: application/json" -H "Authorization: Bearer 7f2ba72ae693b57e18" https://api.tradegecko.com/webhooks/1

### List all webhooks

curl -X GET -H "Content-type: application/json" -H "Authorization: Bearer 7f2ba72ae693b57e18" https://api.tradegecko.com/webhooks

### Get specific webhook

curl -X GET -H "Content-type: application/json" -H "Authorization: Bearer 7f2ba72ae693b57e18" https://api.tradegecko.com/webhooks/1
```

**Comment by futtersack** [comment]
Great, many thanks!! Good luck for the next devs!

**Comment by futtersack** [comment]
Hello @bradleypriest,
it is a long time since your reply, but we still have issues with the webhooks.
sending a GET request for our webhooks, we get the response : 
{"webhooks":[{"id":175464,"created_at":"2017-08-24T17:23:17.239Z","updated_at":"2017-08-24T17:46:46.525Z","event":"variant.create","address":"http://***/webhooks/updateVariant","oauth_application_id":4396}]}
Unfortunatly, creating a new variant through the Tradegecko interface does not fire the webhook... Also, do you know if creating the variant with the API will also fire the webhook? 
Thanks for your support.

**Comment by bradleypriest** [comment]
Hi @futtersack, creating a variant in any way should fire the webhook.
Your server is returning a 405:Method Not Allowed when we POST the webhook so it's not going through

**Comment by futtersack** [comment]
Thanks, working like a charm! Do you think you will also implement the product.update and variant.update events in a near future?

**Comment by bradleypriest** [comment]
They will be implemented, I can't say on how near though

**Comment by adiachenko** [comment]
@bradleypriest Could you please clarify where would updates on webhooks be posted providing there were any breaking changes?

On a side note, is it allowed to use  `variant_image.create` webhook to track and directly reference your S3 images in public facing app (ie: online shop)?

**Comment by bradleypriest** [comment]
Hi @adiachenko we'll definitely update this issue, we're still not 100% on the SSOT for API updates though.

Yeah, go for it, if we decide to move our image hosting we'll be sure to give plenty of notice.

**Comment by IsaacGoldstein** [comment]
could I create two webhooks for the same event ?

**Comment by rkingy** [comment]
Hi @bradleypriest  Just wondering if these webhooks are going to be part of the Tradegecko API documentation?  https://developer.tradegecko.com/ I'm just working through some things now and could really be useful..

**Comment by Thunt108** [comment]
Hi @rkingy 
Nice seeing you here as well. Regarding the webhooks, yes we're planning to publish them in the official documentation in the upcoming months. Will keep you posted on this.
