### ISSUE TITLE
Feature: (bug) Updade variants price list through API doesnt work

### ISSUE THREAD

**Issue by futtersack** [tradegecko/smaug#27]
Hello,
I am trying to update the variant_prices list of a variant object with the API, but the basic prices, ie. retail, wholesale and buy only update through their direct variant attribute.

Thank you for your support

Romain

**Comment by lcpriest** [comment]
Can you please post an example of what you are sending?

**Comment by futtersack** [comment]
Hello,
the payload was {"variant": {"variant_prices": [{"price_list_id": "retail", "value": "22.0"}]}}.  also tried with the "prices" list. The payload works with other prices list, but not with the basic prices like I said.

I also have a problem now trying to upload the stock with the payload {"variant": {"stock_on_hand": "10"}}, nothing is updated and the API returns the 204 code.
Thank you for your help!

**Comment by futtersack** [comment]
Hello,
Still no answers?
Thank you

**Comment by bradleypriest** [comment]
Hi @futtersack,

1) It looks like there is a limitation in our API for the 3 default price lists (retail/wholesale/buy) where they can only be updated via the keys themselves. 
i.e.
```json
{
  variant: {
    retail_price: '22.0'
  }
}
```
I'll pass this on to the API team to see what the implications of updating it are (apps may be relying on the broken behaviour).

2) Stock levels are read-only and can not be manually adjusted by sending the stock level number. We suggest tracking stock levels via the Sales Orders and Purchase Orders they come from, or if it is not an order, via the Stock Adjustments API.

Cheers

**Comment by futtersack** [comment]
Thank you @bradleypriest,

we managed to update the stock with a stock adjustement :) But why this API functionality is not present in the documentation at http://developer.tradegecko.com/??

Best regards

**Comment by bradleypriest** [comment]
Hi @futtersack we've got a few APIs that are still undocumented because we have an internal rule that we only document the stable APIs that won't be changed without extreme fanfare.
The stock adjustments API is still subject to change (we will still do our best to make sure to inform any users well in advance of the switch though)

**Comment by futtersack** [comment]
Hello again,
we now have a problem on the API with the order creation endpoint.
The payload is 
{"order": { 
    "company_id": 11399623, 
    "shipping_address_id": 13783425, 
    "issued_at": "2017-05-04", 
    "order_number": "TEST9999", 
    "billing_address_id": 13783425,
    "order_line_items": [
        {"quantity": 20, "variant_id": 29095374}, 
        {"quantity": 10, "variant_id": 29095371}, ..., 
        {"quantity": 20, "variant_id": 24093578}]
}}
The documentation says that the endpoint accepts embedded order_line_items, but the POST request returns a 422 HTML error code. Without the order_line_items field, the request creates the order.

Thank you

**Comment by bradleypriest** [comment]
Hi @futtersack, what's the response JSON you get with the 422 status?

**Comment by futtersack** [comment]
Hi @bradleypriest, thank you for your answer. I had to incorporate the order_line price, maybe you could change the curl example in the documentation.

Thank you again!

**Comment by bradleypriest** [comment]
Hi @futtersack, we also default to pulling the relevant price from the order's default price list if provided.
I've added a note to the docs to clarify.
Glad it works.
