### ISSUE TITLE
Bug: Updating default_discount_rate through API does not work

### ISSUE THREAD

**Issue by mikewang-fjorge** [tradegecko/smaug#29]
Hello!

I am trying to update a company with the following payload:
```
{
  id: 13771713,
  name: 'fjorge',
  phone_number: '+1 612-877-3841',
  website: 'fjorgedigital.com',
  default_discount_rate: 17
}
```
I'm sending this data to the url `https://api.tradegecko.com/companies/13771713` and getting a 204 status back, indicating success.
However, when I look at the company through the web portal, the other attributes have been updated, but the old discount rate of 14% is still present.
I have also tried turning `default_discount_rate` in the payload into a string, but that did not work either.
Is something incorrect about my syntax, or is this a bug in the API?

**Comment by bradleypriest** [comment]
Hi @mikewang-fjorge, it looks like you've missed out the wrapper key, that format shouldn't update any values on the company.

Try using 
```
{ 
  company: {
    id: 13771713,
    name: 'fjorge',
    phone_number: '+1 612-877-3841',
    website: 'fjorgedigital.com',
    default_discount_rate: 17
  }
}
```

**Comment by mikewang-fjorge** [comment]
@bradleypriest ,

Thank you, that did it! Strangely, the format that I was using before worked when updating the other fields, so I never noticed that my format didn't quite match the API documentation.
