### ISSUE TITLE
missing some }'s in the JSON on the POST examples

### ISSUE THREAD

**Issue by henn0124** [tradegecko/smaug#3]
curl -X POST -H "Content-type: application/json" -H "Authorization: Bearer <ACCESS_TOKEN>"
https://api.tradegecko.com/orders/ -d '{"order":{"company_id":1,"issued_at":"Time.now","billing_address_id":1,"shipping_address_id":1}'

Missing a } at the very end. It should look like this I think.....

curl -X POST -H "Content-type: application/json" -H "Authorization: Bearer <ACCESS_TOKEN>"
https://api.tradegecko.com/orders/ -d '{"order":{"company_id":1,"issued_at":"Time.now","billing_address_id":1,"shipping_address_id":1}}'

**Comment by lcpriest** [comment]
Fixed by https://github.com/tradegecko/smaug/pull/4

**Comment by lcpriest** [comment]
This is great, thanks dude!
