### ISSUE TITLE
Question: connection to API fails with message : {u'message': u"Couldn't find Login with 'id'=61965", u'type': u'Not Found'} 

### ISSUE THREAD

**Issue by futtersack** [tradegecko/smaug#30]
Hello @bradleypriest, @lcpriest, and others!

Since yesterday we get this message when trying to connect to the API :
{u'message': u"Couldn't find Login with 'id'=61965", u'type': u'Not Found'}
I checked the accounts again and the API keys are still well visibles through the website oath/application endpoint.

Could you explain us the problem? The problem is kind of urgent...

Best regards

**Comment by bradleypriest** [comment]
Hi there,
You've set up your keys using a user that has since been deleted from your account.
You'll need to re-auth with an active user.

**Comment by futtersack** [comment]
But I can still view the keys on the user account we use for the API...?

**Comment by bradleypriest** [comment]
That's an oversight on the UI on our part.
We'll get that cleaned up.
Cheers

**Comment by futtersack** [comment]
@bradleypriest I just created a new application from the oath/applications endpoint and still get the same message. The user has not been modified and is still active...

**Comment by bradleypriest** [comment]
Hi @futtersack, you shouldn't need a new Application, just a new token.
Are you using the refresh token flow or the privileged token flow?

**Comment by bradleypriest** [comment]
Also, what's the Login ID in the error message of that one?

**Comment by futtersack** [comment]
We use the privileged token. The user id is pa.regnauld@hovlondon.co.uk

**Comment by bradleypriest** [comment]
Can I get the Login ID returned in the error message please.
`Couldn't find Login with 'id= XXX`

**Comment by futtersack** [comment]
It is in the first post and in the title : 61965

**Comment by bradleypriest** [comment]
That error is for the deleted user.
You mentioned you'd created a new key for an active user and it was still failing with the new key, can you please let me know what the new error message for the new user/key is.

Cheers

**Comment by futtersack** [comment]
We created a new key for this same user. The error message was the same...
Should we created a new user also? As far as I know, this connection problem appears yesterday and no modification has been done on the user. Also we get the message for two differents accounts (but same user).

**Comment by bradleypriest** [comment]
This is very strange, I've just manually revoked the deleted user's credentials.

I'm not seeing a new privileged key being created against the initial application, I do see a completely new application has been created though.

If you just create a new privileged token against the original application and use that, it _should_ work

**Comment by futtersack** [comment]
Ok. I deleted the new application just after seeing it was not functioning. A new privileged token give the same error.
But I asked and there was a problem with this user two days ago (Tickets 132090 and 132344). It seems your engineering team took some actions to solve the issue. The fact is now the user is active but maybe with another id, and creating a new token keep the old id...

**Comment by bradleypriest** [comment]
From our logs I see a lot of successful API requests going through for your application, is there a specific endpoint you're receiving the error from?

**Comment by futtersack** [comment]
No all endpoints answer the same (prices_list, companies, orders, products). The successful requests are logged since yesterday?

**Comment by bradleypriest** [comment]
OK, there's not much more I can do from here. 
Can you please put together an example failing curl script and email it to bradley@tradegecko.com and I'll take a further look.
