### ISSUE TITLE
Questions: How to use embedded variant when adding product?

### ISSUE THREAD

**Issue by basilbegonia** [tradegecko/smaug#37]
Operating system: Ubuntu LTS 16.04
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): NA
Browser version(s): NA
Ruby version (run `ruby -v`):  NA

---

How can I use "embedded variant" when creating a product? In the create product endpoint API docs it states:
"Creates a new product object. This endpoint also accepts embedded variants."

But there is no example of this. I tried adding a "variants" parameter when I made a POST request but the variant was not added. Thanks.

**Comment by bradleypriest** [comment]
Hey @basilbegonia, we should definitely get this added to the API docs.

Here's a light JSON payload to give you an example of the format

```
{
  "product": {
    "brand": "Nitzsche L",
    "name": "Demo Product",
    "product_type": "Tee",
    "opt1": "Colour",
    "variants": [
      {
        "buy_price": "10.0",
        "name": "Squirtle",
        "opt1": "Blue",
        "sku": "123123",
        "variant_prices": [
          {
            "price_list_id": 1,
            "value": "10.0"
          }
        ]
      }
    ]
  }
}
```

**Comment by gregblass** [comment]
+1. How would this be done in Ruby?

**Comment by bradleypriest** [comment]
Hi Greg, please see this article in the Wiki https://github.com/tradegecko/gecko/wiki/Creating-Products-with-Nested-Variants

**Comment by ChaitanyaKandala** [comment]
Can we also send embedded variants while updating a product?
Does it support adding a new variant while updating a product?
