### ISSUE TITLE
Bug? X-Rate-Limit-Reset

### ISSUE THREAD

**Issue by AgilityCC** [tradegecko/smaug#41]
The Rate Limited docs at http://developer.tradegecko.com/#rate-limiting define **X-Rate-Limit-Reset** as:
     "The timestamp (as ms since epoch) when the quota will reset."

However, the values I'm showing are only around 17.5 days... not near enough to be since the epoch of 1/1/1970.  Can anyone help explain this value?

For instance, they have 150933900 as the example value.  That is 17 days, 11 hours, 15 minutes, 39 seconds.

Thank you!

**Comment by bradleypriest** [comment]
Hi @AgilityCC, thanks, looks like a typo in the docs, it should be seconds since epoch, not milliseconds.
Have pushed a fix.
