### ISSUE TITLE
Question: Set "created_at" on Order?

### ISSUE THREAD

**Issue by AgilityCC** [tradegecko/smaug#42]
We are trying to create some past orders (and need the CreatedAt to be last month for reporting reasons).  Is it possible to set the "created_at" variable, or is it ReadOnly?

We are passing it in as "created_at":"2017-11-01T05:00:00Z" but it is being set to the current date/time.

Any way to set it?

Thanks!

**Comment by bradleypriest** [comment]
Hey @AgilityCC, 
The `created_at` field is an internal value, you are looking for the `issued_at` field on the Sales Order, which is user-writable.

Cheers,
Brad

**Comment by AgilityCC** [comment]
Unfortunately, reports seem to look at created_at and not issued_at.

**Comment by bradleypriest** [comment]
Hi @AgilityCC, the reports do work off of `issued_at`, is there a specific report you're seeing using `created_at`?

**Comment by AgilityCC** [comment]
Nevermind.  I was looking at something the wrong way.  Thank you!
