### ISSUE TITLE
Question - Variant - Possible to set "initial_cost"?

### ISSUE THREAD

**Issue by AgilityCC** [tradegecko/smaug#45]
Is it possible to set the "initial_cost" of a variant via the API?

Thanks!

**Comment by RenchChua** [comment]
You can't directly set the initial_cost through the API. What you can do is to create the variants, and then create a purchase_order or stock_adjustment for those variants before creating any sales orders with the quantity and cost that you want to set. That would create a first stock movement that would set the equivalent of the initial_cost for those variants.

**Comment by RenchChua** [comment]
Yes, it can be done. We have updated the documentation to reflect that.
