### ISSUE TITLE
fulfillment vs fulfillments

### ISSUE THREAD

**Issue by JaggedJax** [tradegecko/smaug#7]
The API documentation references the following URL in several places:
`https://api.tradegecko.com/fulfillment/`

It looks like the correct URL should be:
`https://api.tradegecko.com/fulfillments/`

**Comment by lcpriest** [comment]
Solved in https://github.com/tradegecko/smaug/commit/74d52491d3e67af053fde7c7c0b4615aeefe61a0

**Comment by lcpriest** [comment]
Thank you for spotting this!
