### ISSUE TITLE
Getting Sales Order by order_num

### ISSUE THREAD

**Issue by soberanes** [tradegecko/smaug#8]
Hi.

I don't know where to find information about getting an order by order_num with the API.

Is there a method to do this? 

Thanks!

**Comment by lcpriest** [comment]
There is! Same as the rest of the filters, I'll add it to the documentation now.
One note, all filters are on the index endpoint, so it will return an array (usually an array of one).

**Comment by lcpriest** [comment]
Solved in https://github.com/tradegecko/smaug/commit/9e3b4f7a491af804639486ab9fdfef86f3da7339

**Comment by lcpriest** [comment]
Thank you for spotting that :)

**Comment by soberanes** [comment]
I'm going to try that.

Thanks for your reply! :)

**Comment by lcpriest** [comment]
I added it to the documentation now.
`https://api.tradegecko.com/orders?order_number={{order_number}}` should work.

**Comment by soberanes** [comment]
It works! =)

Just a question. The access token expires in two hours after being created, is necessary to refresh the token every two hours? or is there any way to permanently have it.

I'm new with Tradegecko's API.

**Comment by lcpriest** [comment]
If you are integrating with one account, you are able to get a permanent access token:
`https://go.tradegecko.com/oauth/applications/{{id}}`
<img width="780" alt="screenshot 2016-05-02 14 09 00" src="https://cloud.githubusercontent.com/assets/735593/14962961/71464adc-106f-11e6-977b-b9080c438eb4.png">

If you are integrating with many accounts (and want to use OAuth), refreshing the token is the standard way of doing so.

I have a personal project where I have integrated with Google for the analytics system, my method of refreshing a token is pretty straightforward (I just refresh if the expires_at < Time.now)

```
      def access_token
        if expires_at <= DateTime.now
          refresh_token
        end
        client.get('endpoint',  api_token: integration.api_token, refresh_token: integration.refresh_token)
      end
```

This is Ruby code, but I think it's pretty straight forward

**Comment by soberanes** [comment]
All I need is the Privileged Access Tokens for my case. 

Because is a single module and not requires many accounts.

Thanks for your help!
