### ISSUE TITLE
Order line item label is null

### ISSUE THREAD

**Issue by soberanes** [tradegecko/smaug#9]
Hi, 
I need to get the name of the product (line item) from the order. I get the price, discount, etc but label field is NULL. Why? or How can I get the name of the product in the line?

I can't find this in the documentation.

Thanks!

**Comment by lcpriest** [comment]
Hi!

To clarify, an order line item is not a variant (nor is it a product), it's a reference to one. You can fetch it with a second request (by fetching the variant, or a list of variants).

http://developer.tradegecko.com/#retrieve-a-particular-variant

**Comment by lcpriest** [comment]
The order_line_item label is actually used for line items that do not have variants attached to them.
i.e. things like Shipping line items
